# Generated by Django 5.2.7 on 2025-10-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(default='000000000000', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='wilaya',
            field=models.CharField(choices=[('1', 'Wilaya 1'), ('2', 'Wilaya 2'), ('3', 'Wilaya 3'), ('4', 'Wilaya 4'), ('5', 'Wilaya 5'), ('6', 'Wilaya 6'), ('7', 'Wilaya 7'), ('8', 'Wilaya 8'), ('9', 'Wilaya 9'), ('10', 'Wilaya 10'), ('11', 'Wilaya 11'), ('12', 'Wilaya 12'), ('13', 'Wilaya 13'), ('14', 'Wilaya 14'), ('15', 'Wilaya 15'), ('16', 'Wilaya 16'), ('17', 'Wilaya 17'), ('18', 'Wilaya 18'), ('19', 'Wilaya 19'), ('20', 'Wilaya 20'), ('21', 'Wilaya 21'), ('22', 'Wilaya 22'), ('23', 'Wilaya 23'), ('24', 'Wilaya 24'), ('25', 'Wilaya 25'), ('26', 'Wilaya 26'), ('27', 'Wilaya 27'), ('28', 'Wilaya 28'), ('29', 'Wilaya 29'), ('30', 'Wilaya 30'), ('31', 'Wilaya 31'), ('32', 'Wilaya 32'), ('33', 'Wilaya 33'), ('34', 'Wilaya 34'), ('35', 'Wilaya 35'), ('36', 'Wilaya 36'), ('37', 'Wilaya 37'), ('38', 'Wilaya 38'), ('39', 'Wilaya 39'), ('40', 'Wilaya 40'), ('41', 'Wilaya 41'), ('42', 'Wilaya 42'), ('43', 'Wilaya 43'), ('44', 'Wilaya 44'), ('45', 'Wilaya 45'), ('46', 'Wilaya 46'), ('47', 'Wilaya 47'), ('48', 'Wilaya 48'), ('49', 'Wilaya 49'), ('50', 'Wilaya 50'), ('51', 'Wilaya 51'), ('52', 'Wilaya 52'), ('53', 'Wilaya 53'), ('54', 'Wilaya 54'), ('55', 'Wilaya 55'), ('56', 'Wilaya 56'), ('57', 'Wilaya 57'), ('58', 'Wilaya 58')], max_length=2),
        ),
    ]
